class_name Match3Events
extends RefCounted

## Event ids for the service-first Match3 loop (mirrors Unity Match3Events).

const REQUEST_MATCH3_MOVE := "REQUEST_MATCH3_MOVE"
const REQUEST_MATCH3_RESET := "REQUEST_MATCH3_RESET"
const REQUEST_MATCH3_BEGIN_LEVEL := "REQUEST_MATCH3_BEGIN_LEVEL"
const REQUEST_MATCH3_BOARD_SETTLED := "REQUEST_MATCH3_BOARD_SETTLED"
const REQUEST_MATCH3_SET_GAME_STATUS := "REQUEST_MATCH3_SET_GAME_STATUS"

const FACT_MATCH3_EPHEMERAL_SERVICE_STARTED := "FACT_MATCH3_EPHEMERAL_SERVICE_STARTED"
const FACT_MATCH3_EPHEMERAL_SERVICE_STOPPED := "FACT_MATCH3_EPHEMERAL_SERVICE_STOPPED"
const FACT_MATCH3_BOARD_RESET := "FACT_MATCH3_BOARD_RESET"
const FACT_MATCH3_BOARD_CHANGED := "FACT_MATCH3_BOARD_CHANGED"
const FACT_MATCH3_MOVE_RESOLVED := "FACT_MATCH3_MOVE_RESOLVED"
const FACT_MATCH3_STATUS_CHANGED := "FACT_MATCH3_STATUS_CHANGED"
const FACT_MATCH3_SHUFFLE_USED := "FACT_MATCH3_SHUFFLE_USED"

const PAYLOAD_LEVEL_NUMBER := "levelNumber"
const PAYLOAD_GAME_STATUS := "gameStatus"
const PAYLOAD_SCORE := "currentScore"
const PAYLOAD_SCORE_TO_WIN := "targetScore"
const PAYLOAD_CURRENT_MOVES := "currentMoves"
const PAYLOAD_SHUFFLES_REMAINING := "currentShuffles"
const PAYLOAD_WIDTH := "width"
const PAYLOAD_HEIGHT := "height"
const PAYLOAD_TILES := "tiles"
