class_name FallingBlockEvents
extends RefCounted

## Event ids and payload keys for the Ultravibe FallingBlock systems.
## Ported from FallingBlockEvents.partial.cs.

# --- Input ---
const REQUEST_FALLING_BLOCK_INPUT = "REQUEST_FALLING_BLOCK_INPUT"
const FACT_FALLING_BLOCK_INPUT_PROCESSED = "FACT_FALLING_BLOCK_INPUT_PROCESSED"
const FACT_FALLING_BLOCK_INPUT_DENIED = "FACT_FALLING_BLOCK_INPUT_DENIED"

# --- Spawn pipeline ---
const REQUEST_FALLING_BLOCK_SPAWN_PIECE = "REQUEST_FALLING_BLOCK_SPAWN_PIECE"
const FACT_FALLING_BLOCK_SPAWN_NEEDED = "FACT_FALLING_BLOCK_SPAWN_NEEDED"
const FACT_FALLING_BLOCK_SPAWN_PIECE_READY = "FACT_FALLING_BLOCK_SPAWN_PIECE_READY"
const FACT_FALLING_BLOCK_SPAWN_DENIED = "FACT_FALLING_BLOCK_SPAWN_DENIED"

# --- Deck mutation ---
const REQUEST_FALLING_BLOCK_DECK_ADD_ENTRY = "REQUEST_FALLING_BLOCK_DECK_ADD_ENTRY"
const FACT_FALLING_BLOCK_DECK_ADD_ENTRY_CONFIRMED = "FACT_FALLING_BLOCK_DECK_ADD_ENTRY_CONFIRMED"
const FACT_FALLING_BLOCK_DECK_ADD_ENTRY_DENIED = "FACT_FALLING_BLOCK_DECK_ADD_ENTRY_DENIED"
const REQUEST_FALLING_BLOCK_DECK_ADD_RANDOM_ENTRY = "REQUEST_FALLING_BLOCK_DECK_ADD_RANDOM_ENTRY"
const FACT_FALLING_BLOCK_DECK_ADD_RANDOM_ENTRY_CONFIRMED = "FACT_FALLING_BLOCK_DECK_ADD_RANDOM_ENTRY_CONFIRMED"
const FACT_FALLING_BLOCK_DECK_ADD_RANDOM_ENTRY_DENIED = "FACT_FALLING_BLOCK_DECK_ADD_RANDOM_ENTRY_DENIED"
const REQUEST_FALLING_BLOCK_DECK_REMOVE_ENTRY = "REQUEST_FALLING_BLOCK_DECK_REMOVE_ENTRY"
const FACT_FALLING_BLOCK_DECK_REMOVE_ENTRY_CONFIRMED = "FACT_FALLING_BLOCK_DECK_REMOVE_ENTRY_CONFIRMED"
const FACT_FALLING_BLOCK_DECK_REMOVE_ENTRY_DENIED = "FACT_FALLING_BLOCK_DECK_REMOVE_ENTRY_DENIED"

# --- Line clear / scoring / rounds ---
const FACT_FALLING_BLOCK_LINE_CLEAR_CALLOUT = "FACT_FALLING_BLOCK_LINE_CLEAR_CALLOUT"
const REQUEST_OBJECTIVE_CONTRIBUTION_FROM_LINE_CLEAR = "REQUEST_OBJECTIVE_CONTRIBUTION_FROM_LINE_CLEAR"
const FACT_OBJECTIVE_FROM_LINE_CLEAR_RESOLVED = "FACT_OBJECTIVE_FROM_LINE_CLEAR_RESOLVED"
const FACT_FALLING_BLOCK_ROUND_ADVANCED = "FACT_FALLING_BLOCK_ROUND_ADVANCED"
const FACT_FALLING_BLOCK_ROUND_LINES_UPDATED = "FACT_FALLING_BLOCK_ROUND_LINES_UPDATED"
const FACT_FALLING_BLOCK_GAME_OVER = "FACT_FALLING_BLOCK_GAME_OVER"
const FACT_FALLING_BLOCK_PIECE_LOCKED = "FACT_FALLING_BLOCK_PIECE_LOCKED"

# --- Boss encounters ---
const FACT_FALLING_BLOCK_BOSS_ENCOUNTER_STARTED = "FACT_FALLING_BLOCK_BOSS_ENCOUNTER_STARTED"
const FACT_FALLING_BLOCK_BOSS_ENCOUNTER_SURVIVED = "FACT_FALLING_BLOCK_BOSS_ENCOUNTER_SURVIVED"

# --- Payload keys ---
const PAYLOAD_PLAYER_ID = "playerId"
const PAYLOAD_SPAWN_REASON = "spawnReason"
const PAYLOAD_SPAWN_FROM_DECK_ENTRIES = "spawnFromDeckEntries"
const PAYLOAD_INPUT_TYPE = "inputType"
const PAYLOAD_ALLOWED = "allowed"
const PAYLOAD_ULTRAVIBE_ID = "ultravibeId"
const PAYLOAD_ULTRAVIBE_BLOCKS_COUNT = "ultravibeBlocksCount"
const PAYLOAD_SPAWN_VARIANT_TAGS = "variantTags"
const PAYLOAD_SPAWN_ULTRAVIBE_TAGS = "ultravibeTags"
const PAYLOAD_SPAWN_MERGED_TAGS = "tags"
const PAYLOAD_SPAWN_COLOR_FLAGS = "colors"
const PAYLOAD_VARIANT_ID = "variantId"
const PAYLOAD_DISCARD_ADD_AMOUNT = "amount"
const PAYLOAD_DECK_ENTRY_ID = "deckEntryId"
const PAYLOAD_DROP_DISTANCE = "dropDistance"
## Placement-flash geometry (attached to the piece-locked fact) used to drive the
## legacy hard-drop "slam" flash: horizontal piece center, bottom row, and width.
const PAYLOAD_CENTER_GRID_X = "centerGridX"
const PAYLOAD_BOTTOM_GRID_Y = "bottomGridY"
const PAYLOAD_COLUMN_COUNT = "columnCount"
const PAYLOAD_RAW_LINES_CLEARED = "rawLinesCleared"
## Cleared-cell snapshot (captured before collapse) used to drive the legacy
## white line-clear flash. A list of {gridX, gridY, variantId} objects, where
## gridY is the visible (drawn) row index.
const PAYLOAD_CLEAR_CELLS = "clearCells"
const PAYLOAD_CLEAR_CELL_GRID_X = "gridX"
const PAYLOAD_CLEAR_CELL_GRID_Y = "gridY"
const PAYLOAD_CLEAR_CELL_VARIANT_ID = "variantId"
const PAYLOAD_OBJECTIVE_POINTS = "objectivePoints"
const PAYLOAD_OBJECTIVE_MULTI = "objectiveMulti"
const PAYLOAD_OBJECTIVE_DELTA = "objectiveDelta"
const PAYLOAD_ROUND_LINES_CURRENT = "roundLinesCurrent"
const PAYLOAD_ROUND_LINES_NEEDED = "roundLinesNeeded"
const PAYLOAD_ROUND_NUMBER = "roundNumber"
const PAYLOAD_COMPLETED_ROUND = "completedRound"
const PAYLOAD_COMPLETED_ROUND_LINES_NEEDED = "completedRoundLinesNeeded"
const PAYLOAD_ELAPSED_SEC = "elapsedSec"
const PAYLOAD_BOSS_ENCOUNTER_LEVEL_ID = "bossEncounterLevelId"
const PAYLOAD_BOSS_ENCOUNTERS_SURVIVED_THIS_RUN = "bossEncountersSurvivedThisRun"
